//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Action) DeepCopyInto(out *Action) {
	*out = *in
	if in.Delete != nil {
		in, out := &in.Delete, &out.Delete
		*out = new(DeleteAction)
		**out = **in
	}
	if in.ForceMerge != nil {
		in, out := &in.ForceMerge, &out.ForceMerge
		*out = new(ForceMergeAction)
		(*in).DeepCopyInto(*out)
	}
	if in.ReadOnly != nil {
		in, out := &in.ReadOnly, &out.ReadOnly
		*out = new(ReadOnlyAction)
		**out = **in
	}
	if in.RollOver != nil {
		in, out := &in.RollOver, &out.RollOver
		*out = new(RollOverAction)
		**out = **in
	}
	if in.Snapshot != nil {
		in, out := &in.Snapshot, &out.Snapshot
		*out = new(SnapshotAction)
		**out = **in
	}
	if in.ReadWrite != nil {
		in, out := &in.ReadWrite, &out.ReadWrite
		*out = new(ReadWriteAction)
		**out = **in
	}
	if in.ReplicaCount != nil {
		in, out := &in.ReplicaCount, &out.ReplicaCount
		*out = new(ReplicaCountAction)
		**out = **in
	}
	if in.Shrink != nil {
		in, out := &in.Shrink, &out.Shrink
		*out = new(ShrinkAction)
		**out = **in
	}
	if in.Close != nil {
		in, out := &in.Close, &out.Close
		*out = new(CloseAction)
		**out = **in
	}
	if in.Open != nil {
		in, out := &in.Open, &out.Open
		*out = new(OpenAction)
		**out = **in
	}
	if in.Notification != nil {
		in, out := &in.Notification, &out.Notification
		*out = new(NotifyAction)
		**out = **in
	}
	if in.ConvertIndexToRemote != nil {
		in, out := &in.ConvertIndexToRemote, &out.ConvertIndexToRemote
		*out = new(ConvertIndexToRemoteAction)
		**out = **in
	}
	if in.IndexPriority != nil {
		in, out := &in.IndexPriority, &out.IndexPriority
		*out = new(IndexPriorityAction)
		**out = **in
	}
	if in.Allocation != nil {
		in, out := &in.Allocation, &out.Allocation
		*out = new(AllocationAction)
		**out = **in
	}
	if in.Rollup != nil {
		in, out := &in.Rollup, &out.Rollup
		*out = new(RollupAction)
		**out = **in
	}
	if in.StopReplication != nil {
		in, out := &in.StopReplication, &out.StopReplication
		*out = new(StopReplicationAction)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Action.
func (in *Action) DeepCopy() *Action {
	if in == nil {
		return nil
	}
	out := new(Action)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllocationAction) DeepCopyInto(out *AllocationAction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllocationAction.
func (in *AllocationAction) DeepCopy() *AllocationAction {
	if in == nil {
		return nil
	}
	out := new(AllocationAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloseAction) DeepCopyInto(out *CloseAction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloseAction.
func (in *CloseAction) DeepCopy() *CloseAction {
	if in == nil {
		return nil
	}
	out := new(CloseAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConvertIndexToRemoteAction) DeepCopyInto(out *ConvertIndexToRemoteAction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConvertIndexToRemoteAction.
func (in *ConvertIndexToRemoteAction) DeepCopy() *ConvertIndexToRemoteAction {
	if in == nil {
		return nil
	}
	out := new(ConvertIndexToRemoteAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeleteAction) DeepCopyInto(out *DeleteAction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteAction.
func (in *DeleteAction) DeepCopy() *DeleteAction {
	if in == nil {
		return nil
	}
	out := new(DeleteAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForceMerge) DeepCopyInto(out *ForceMerge) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForceMerge.
func (in *ForceMerge) DeepCopy() *ForceMerge {
	if in == nil {
		return nil
	}
	out := new(ForceMerge)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForceMergeAction) DeepCopyInto(out *ForceMergeAction) {
	*out = *in
	if in.ForceMerge != nil {
		in, out := &in.ForceMerge, &out.ForceMerge
		*out = new(ForceMerge)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForceMergeAction.
func (in *ForceMergeAction) DeepCopy() *ForceMergeAction {
	if in == nil {
		return nil
	}
	out := new(ForceMergeAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ISMTemplate) DeepCopyInto(out *ISMTemplate) {
	*out = *in
	if in.IndexPatterns != nil {
		in, out := &in.IndexPatterns, &out.IndexPatterns
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ISMTemplate.
func (in *ISMTemplate) DeepCopy() *ISMTemplate {
	if in == nil {
		return nil
	}
	out := new(ISMTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IndexPriorityAction) DeepCopyInto(out *IndexPriorityAction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IndexPriorityAction.
func (in *IndexPriorityAction) DeepCopy() *IndexPriorityAction {
	if in == nil {
		return nil
	}
	out := new(IndexPriorityAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotifyAction) DeepCopyInto(out *NotifyAction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotifyAction.
func (in *NotifyAction) DeepCopy() *NotifyAction {
	if in == nil {
		return nil
	}
	out := new(NotifyAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OSIndexPolicy) DeepCopyInto(out *OSIndexPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OSIndexPolicy.
func (in *OSIndexPolicy) DeepCopy() *OSIndexPolicy {
	if in == nil {
		return nil
	}
	out := new(OSIndexPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OSIndexPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OSIndexPolicyList) DeepCopyInto(out *OSIndexPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OSIndexPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OSIndexPolicyList.
func (in *OSIndexPolicyList) DeepCopy() *OSIndexPolicyList {
	if in == nil {
		return nil
	}
	out := new(OSIndexPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OSIndexPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OSIndexPolicySpec) DeepCopyInto(out *OSIndexPolicySpec) {
	*out = *in
	out.OpensearhConnection = in.OpensearhConnection
	in.Policy.DeepCopyInto(&out.Policy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OSIndexPolicySpec.
func (in *OSIndexPolicySpec) DeepCopy() *OSIndexPolicySpec {
	if in == nil {
		return nil
	}
	out := new(OSIndexPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OSIndexPolicyStatus) DeepCopyInto(out *OSIndexPolicyStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OSIndexPolicyStatus.
func (in *OSIndexPolicyStatus) DeepCopy() *OSIndexPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(OSIndexPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenAction) DeepCopyInto(out *OpenAction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenAction.
func (in *OpenAction) DeepCopy() *OpenAction {
	if in == nil {
		return nil
	}
	out := new(OpenAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpensearchIndexPolicy) DeepCopyInto(out *OpensearchIndexPolicy) {
	*out = *in
	if in.ErrorNotification != nil {
		in, out := &in.ErrorNotification, &out.ErrorNotification
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.States != nil {
		in, out := &in.States, &out.States
		*out = make([]*State, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(State)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.ISMTemplate != nil {
		in, out := &in.ISMTemplate, &out.ISMTemplate
		*out = new(ISMTemplate)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpensearchIndexPolicy.
func (in *OpensearchIndexPolicy) DeepCopy() *OpensearchIndexPolicy {
	if in == nil {
		return nil
	}
	out := new(OpensearchIndexPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpensearhConnection) DeepCopyInto(out *OpensearhConnection) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpensearhConnection.
func (in *OpensearhConnection) DeepCopy() *OpensearhConnection {
	if in == nil {
		return nil
	}
	out := new(OpensearhConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReadOnlyAction) DeepCopyInto(out *ReadOnlyAction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReadOnlyAction.
func (in *ReadOnlyAction) DeepCopy() *ReadOnlyAction {
	if in == nil {
		return nil
	}
	out := new(ReadOnlyAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReadWriteAction) DeepCopyInto(out *ReadWriteAction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReadWriteAction.
func (in *ReadWriteAction) DeepCopy() *ReadWriteAction {
	if in == nil {
		return nil
	}
	out := new(ReadWriteAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicaCountAction) DeepCopyInto(out *ReplicaCountAction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicaCountAction.
func (in *ReplicaCountAction) DeepCopy() *ReplicaCountAction {
	if in == nil {
		return nil
	}
	out := new(ReplicaCountAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RollOverAction) DeepCopyInto(out *RollOverAction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RollOverAction.
func (in *RollOverAction) DeepCopy() *RollOverAction {
	if in == nil {
		return nil
	}
	out := new(RollOverAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RollupAction) DeepCopyInto(out *RollupAction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RollupAction.
func (in *RollupAction) DeepCopy() *RollupAction {
	if in == nil {
		return nil
	}
	out := new(RollupAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShrinkAction) DeepCopyInto(out *ShrinkAction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShrinkAction.
func (in *ShrinkAction) DeepCopy() *ShrinkAction {
	if in == nil {
		return nil
	}
	out := new(ShrinkAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotAction) DeepCopyInto(out *SnapshotAction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotAction.
func (in *SnapshotAction) DeepCopy() *SnapshotAction {
	if in == nil {
		return nil
	}
	out := new(SnapshotAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *State) DeepCopyInto(out *State) {
	*out = *in
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]*Action, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Action)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Transitions != nil {
		in, out := &in.Transitions, &out.Transitions
		*out = make([]*Transition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Transition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new State.
func (in *State) DeepCopy() *State {
	if in == nil {
		return nil
	}
	out := new(State)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StopReplicationAction) DeepCopyInto(out *StopReplicationAction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StopReplicationAction.
func (in *StopReplicationAction) DeepCopy() *StopReplicationAction {
	if in == nil {
		return nil
	}
	out := new(StopReplicationAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Transition) DeepCopyInto(out *Transition) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Transition.
func (in *Transition) DeepCopy() *Transition {
	if in == nil {
		return nil
	}
	out := new(Transition)
	in.DeepCopyInto(out)
	return out
}
