# This rule is not used by the project opensearch-ism-crd itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over batch.a8uhnf.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: opensearch-ism-crd
    app.kubernetes.io/managed-by: kustomize
  name: osindexpolicy-admin-role
rules:
- apiGroups:
  - batch.a8uhnf.com
  resources:
  - osindexpolicies
  verbs:
  - '*'
- apiGroups:
  - batch.a8uhnf.com
  resources:
  - osindexpolicies/status
  verbs:
  - get
