apiVersion: batch.a8uhnf.com/v1
kind: OSIndexPolicy
metadata:
  labels:
    app.kubernetes.io/name: opensearch-ism-crd
    app.kubernetes.io/managed-by: kustomize
  name: osindexpolicy-sample
spec:
  # TODO(user): Add fields here
  opensearch_connection:
    host: "opensearch.default.svc.cluster.local"
    port: 9200
    scheme: "https"
    # username: "admin"
    # password: "admin_password"